# -*- coding: utf-8 -*-

class LANG_CODE:
	AA = 'aa'
	AB = 'ab'
	AF = 'af'
	AM = 'am'
	AR = 'ar'
	AS = 'as'
	AY = 'ay'
	AZ = 'az'
	BA = 'ba'
	BE = 'be'
	BG = 'bg'
	BH = 'bh'
	BI = 'bi'
	BN = 'bn'
	BO = 'bo'
	BR = 'br'
	BS = 'bs'
	CA = 'ca'
	CN = 'cn'
	CO = 'co'
	CS = 'cs'
	CY = 'cy'
	DA = 'da'
	DE = 'de'
	DZ = 'dz'
	EL = 'el'
	EN = 'en'
	EO = 'eo'
	ES = 'es'
	ET = 'et'
	EU = 'eu'
	FA = 'fa'
	FI = 'fi'
	FJ = 'fj'
	FO = 'fo'
	FR = 'fr'
	FY = 'fy'
	GA = 'ga'
	GD = 'gd'
	GL = 'gl'
	GN = 'gn'
	GU = 'gu'
	HA = 'ha'
	HE = 'he'
	HI = 'hi'
	HR = 'hr'
	HU = 'hu'
	HY = 'hy'
	IA = 'ia'
	ID = 'id'
	IE = 'ie'
	IK = 'ik'
	IS = 'is'
	IT = 'it'
	IU = 'iu'
	JA = 'ja'
	JI = 'ji'
	JW = 'jw'
	KA = 'ka'
	KK = 'kk'
	KL = 'kl'
	KM = 'km'
	KN = 'kn'
	KO = 'ko'
	KS = 'ks'
	KU = 'ku'
	KY = 'ky'
	LA = 'la'
	LN = 'ln'
	LO = 'lo'
	LT = 'lt'
	LV = 'lv'
	MG = 'mg'
	MI = 'mi'
	MK = 'mk'
	ML = 'ml'
	MN = 'mn'
	MO = 'mo'
	MR = 'mr'
	MS = 'ms'
	MT = 'mt'
	MY = 'my'
	NA = 'na'
	NE = 'ne'
	NL = 'nl'
	NO = 'no'
	OC = 'oc'
	OM = 'om'
	OR = 'or'
	PA = 'pa'
	PL = 'pl'
	PS = 'ps'
	PT = 'pt'
	QU = 'qu'
	RM = 'rm'
	RN = 'rn'
	RO = 'ro'
	RU = 'ru'
	RW = 'rw'
	SA = 'sa'
	SD = 'sd'
	SG = 'sg'
	SH = 'sh'
	SI = 'si'
	SK = 'sk'
	SL = 'sl'
	SM = 'sm'
	SN = 'sn'
	SO = 'so'
	SQ = 'sq'
	SR = 'sr'
	SS = 'ss'
	ST = 'st'
	SU = 'su'
	SV = 'sv'
	SW = 'sw'
	TA = 'ta'
	TE = 'te'
	TG = 'tg'
	TH = 'th'
	TI = 'ti'
	TK = 'tk'
	TL = 'tl'
	TN = 'tn'
	TO = 'to'
	TR = 'tr'
	TS = 'ts'
	TT = 'tt'
	TW = 'tw'
	UK = 'uk'
	UR = 'ur'
	UZ = 'uz'
	VI = 'vi'
	VO = 'vo'
	WO = 'wo'
	XH = 'xh'
	XX = 'xx'
	YO = 'yo'
	ZH = 'zh'
	ZU = 'zu'

class LANG:
	ACTION = 30213
	ANIMATED = 30214
	ADVENTURE = 30215
	DOCUMENTARY = 30216
	DRAMA = 30217
	EROTIC = 30218
	FANTASY = 30219
	HISTORICAL = 30220
	HORROR = 30221
	MUSIC = 30222
	IMAX = 30223
	CATASTROPHIC = 30224
	COMEDY = 30225
	SHORT = 30226
	CRIME = 30227
	MUSICAL = 30228
	MYSTERIOUS = 30229
	EDUCATIONAL = 30230
	FAIRYTALE = 30231
	PORNOGRAPHIC = 30232
	PSYCHOLOGICAL = 30233
	JOURNALISTIC = 30234
	REALITY = 30235
	TRAVEL = 30236
	FAMILY = 30237
	ROMANTIC = 30238
	SCI_FI = 30239
	COMPETITION = 30240
	SPORTS = 30241
	STAND_UP = 30242
	TALK_SHOW = 30243
	TELENOVELA = 30244
	THRILLER = 30245
	MILITARY = 30246
	WESTERN = 30247
	BIOGRAPHICAL = 30248
	ANIMATION = 30249

	# COUNTRIES
	ALGERIA = 31000
	ARGENTINA = 31001
	ARMENIA = 31002
	ARUBA = 31003
	AUSTRALIA = 31004
	AUSTRIA = 31005
	AZERBAIJAN = 31006
	BAHAMAS = 31007
	BANGLADESH = 31008
	BELARUS = 31009
	BELGIUM = 31010
	BHUTAN = 31011
	BOLIVIA = 31012
	BOSNIA_AND_HERZEGOVINA = 31013
	BOTSWANA = 31014
	BRAZIL = 31015
	BRUNEI = 31016
	BULGARIA = 31017
	CAMBODIA = 31018
	CANADA = 31019
	CHILE = 31020
	CHINA = 31021
	COLOMBIA = 31022
	COSTA_RICA = 31023
	CROATIA = 31024
	CUBA = 31025
	CYPRUS = 31026
	CZECHIA = 31027
	CZECHOSLOVAKIA = 31028
	DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 31029
	DENMARK = 31030
	DOMINICAN_REPUBLIC = 31031
	EAST_GERMANY = 31032
	EGYPT = 31033
	ESTONIA = 31034
	FED_REP_YUGOSLAVIA = 31035
	FINLAND = 31036
	FRANCE = 31037
	FRENCH_POLYNESIA = 31038
	GEORGIA = 31039
	GERMAN_EMPIRE = 31040
	GERMANY = 31041
	GHANA = 31042
	GREECE = 31043
	HAITI = 31044
	HONG_KONG = 31045
	HUNGARY = 31046
	ICELAND = 31047
	INDIA = 31048
	INDONESIA = 31049
	IRAN = 31050
	IRAQ = 31051
	IRELAND = 31052
	ISRAEL = 31053
	ITALY = 31054
	JAMAICA = 31055
	JAPAN = 31056
	JORDAN = 31057
	KAZAKHSTAN = 31058
	KENYA = 31059
	LAOS = 31060
	LATVIA = 31061
	LEBANON = 31062
	LICHTENSTEIN = 31063
	LITHUANIA = 31064
	LUXEMBOURG = 31065
	MACAO = 31066
	MACEDONIA = 31067
	MALAYSIA = 31068
	MALTA = 31069
	MEXICO = 31070
	MONACO = 31071
	MONGOLIA = 31072
	MONTENEGRO = 31073
	MOROCCO = 31074
	NAMIBIA = 31075
	NEPAL = 31076
	NETHERLANDS = 31077
	NEW_ZEALAND = 31078
	NIGERIA = 31079
	NORTH_KOREA = 31080
	NORWAY = 31081
	PAKISTAN = 31082
	PALESTINE = 31083
	PANAMA = 31084
	PAPUA_NEW_GUINEA = 31085
	PARAGUAY = 31086
	PERU = 31087
	PHILIPPINES = 31088
	POLAND = 31089
	PORTUGAL = 31090
	PUERTO_RICO = 31091
	QATAR = 31092
	ROMANIA = 31093
	RUSSIA = 31094
	SAUDI_ARABIA = 31095
	SENEGAL = 31096
	SERBIA = 31097
	SERBIA_AND_MONTENEGRO = 31098
	SINGAPORE = 31099
	SLOVAKIA = 31100
	SLOVENIA = 31101
	SOUTH_AFRICAN_REPUBLIC = 31102
	SOUTH_KOREA = 31103
	SPAIN = 31104
	SWEDEN = 31105
	SWITZERLAND = 31106
	SYRIA = 31107
	TAIWAN = 31108
	TANZANIA = 31109
	THAILAND = 31110
	THE_SOVIET_UNION = 31111
	TUNISIA = 31112
	TURKEY = 31113
	UGANDA = 31114
	UKRAINE = 31115
	UNITED_ARAB_EMIRATES = 31116
	UNITED_KINGDOM = 31117
	UNITED_STATES_OF_AMERICA = 31118
	URUGUAY = 31119
	VENEZUELA = 31120
	VIETNAM = 31121
	WEST_GERMANY = 31122
	YUGOSLAVIA = 31123
	ZIMBABWE = 31124

	# LANGUAGES
	AFAR = 32000
	ABKHAZIAN = 32001
	AFRIKAANS = 32002
	AMHARIC = 32003
	ARABIC = 32004
	ASSAMESE = 32005
	AYMARA = 32006
	AZERBAIJANI = 32007
	BASHKIR = 32008
	BYELORUSSIAN = 32009
	BULGARIAN = 32010
	BIHARI = 32011
	BISLAMA = 32012
	BENGALI_BANGLA = 32013
	TIBETAN = 32014
	BRETON = 32015
	CATALAN = 32016
	CORSICAN = 32017
	CZECH = 32018
	WELSH = 32019
	DANISH = 32020
	GERMAN = 32021
	BHUTANI = 32022
	GREEK = 32023
	ENGLISH = 32024
	ESPERANTO = 32025
	SPANISH = 32026
	ESTONIAN = 32027
	BASQUE = 32028
	PERSIAN = 32029
	FINNISH = 32030
	FIJI = 32031
	FAEROESE = 32032
	FRENCH = 32033
	FRISIAN = 32034
	IRISH = 32035
	SCOTS_GAELIC = 32036
	GALICIAN = 32037
	GUARANI = 32038
	GUJARATI = 32039
	HAUSA = 32040
	HEBREW = 32041
	HINDI = 32042
	CROATIAN = 32043
	HUNGARIAN = 32044
	ARMENIAN = 32045
	INTERLINGUA = 32046
	INDONESIAN = 32047
	INTERLINGUE = 32048
	INUPIAK = 32049
	ICELANDIC = 32050
	ITALIAN = 32051
	JAPANESE = 32052
	YIDDISH = 32053
	JAVANESE = 32054
	GEORGIAN = 32055
	KAZAKH = 32056
	GREENLANDIC = 32057
	CAMBODIAN = 32058
	KANNADA = 32059
	KOREAN = 32060
	KASHMIRI = 32061
	KURDISH = 32062
	KIRGHIZ = 32063
	LATIN = 32064
	LINGALA = 32065
	LAOTHIAN = 32066
	LITHUANIAN = 32067
	LATVIAN_LETTISH = 32068
	MALAGASY = 32069
	MAORI = 32070
	MACEDONIAN = 32071
	MALAYALAM = 32072
	MONGOLIAN = 32073
	MOLDAVIAN = 32074
	MARATHI = 32075
	MALAY = 32076
	MALTESE = 32077
	BURMESE = 32078
	NAURU = 32079
	NEPALI = 32080
	DUTCH = 32081
	NORWEGIAN = 32082
	OCCITAN = 32083
	OROMO = 32084
	ORIYA = 32085
	PUNJABI = 32086
	POLISH = 32087
	PASHTO_PUSHTO = 32088
	PORTUGUESE = 32089
	QUECHUA = 32090
	RHAETO_ROMANCE = 32091
	KIRUNDI = 32092
	ROMANIAN = 32093
	RUSSIAN = 32094
	KINYARWANDA = 32095
	SANSKRIT = 32096
	SINDHI = 32097
	SANGRO = 32098
	SERBO_CROATIAN = 32099
	SINGHALESE = 32100
	SLOVAK = 32101
	SLOVENIAN = 32102
	SAMOAN = 32103
	SHONA = 32104
	SOMALI = 32105
	ALBANIAN = 32106
	SERBIAN = 32107
	SISWATI = 32108
	SESOTHO = 32109
	SUNDANESE = 32110
	SWEDISH = 32111
	SWAHILI = 32112
	TAMIL = 32113
	TEGULU = 32114
	TAJIK = 32115
	THAI = 32116
	TIGRINYA = 32117
	TURKMEN = 32118
	TAGALOG = 32119
	SETSWANA = 32120
	TONGA = 32121
	TURKISH = 32122
	TSONGA = 32123
	TATAR = 32124
	TWI = 32125
	UKRAINIAN = 32126
	URDU = 32127
	UZBEK = 32128
	VIETNAMESE = 32129
	VOLAPUK = 32130
	WOLOF = 32131
	XHOSA = 32132
	YORUBA = 32133
	CHINESE = 32134
	ZULU = 32135
	BOSNIAN = 32136
	INUKTITUT = 32137
	NO_LANGUAGE = 32138

class COUNTRY:
	ALGERIA = 'Algeria'
	ARGENTINA = 'Argentina'
	ARMENIA = 'Armenia'
	ARUBA = 'Aruba'
	AUSTRALIA = 'Australia'
	AUSTRIA = 'Austria'
	AZERBAIJAN = 'Azerbaijan'
	BAHAMAS = 'Bahamas'
	BANGLADESH = 'Bangladesh'
	BELARUS = 'Belarus'
	BELGIUM = 'Belgium'
	BHUTAN = 'Bhutan'
	BOLIVIA = 'Bolivia'
	BOSNIA_AND_HERZEGOVINA = 'Bosnia and Herzegovina'
	BOTSWANA = 'Botswana'
	BRAZIL = 'Brazil'
	BRUNEI = 'Brunei'
	BULGARIA = 'Bulgaria'
	CAMBODIA = 'Cambodia'
	CANADA = 'Canada'
	CHILE = 'Chile'
	CHINA = 'China'
	COLOMBIA = 'Colombia'
	COSTA_RICA = 'Costa Rica'
	CROATIA = 'Croatia'
	CUBA = 'Cuba'
	CYPRUS = 'Cyprus'
	CZECHIA = 'Czechia'
	CZECHOSLOVAKIA = 'Czechoslovakia'
	DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 'Democratic Republic of the Congo'
	DENMARK = 'Denmark'
	DOMINICAN_REPUBLIC = 'Dominican republic'
	EAST_GERMANY = 'East Germany'
	EGYPT = 'Egypt'
	ESTONIA = 'Estonia'
	FED_REP_YUGOSLAVIA = 'Fed. Rep. Yugoslavia'
	FINLAND = 'Finland'
	FRANCE = 'France'
	FRENCH_POLYNESIA = 'French Polynesia'
	GEORGIA = 'Georgia'
	GERMAN_EMPIRE = 'German Empire'
	GERMANY = 'Germany'
	GHANA = 'Ghana'
	GREECE = 'Greece'
	HAITI = 'Haiti'
	HONG_KONG = 'Hong Kong'
	HUNGARY = 'Hungary'
	ICELAND = 'Iceland'
	INDIA = 'India'
	INDONESIA = 'Indonesia'
	IRAN = 'Iran'
	IRAQ = 'Iraq'
	IRELAND = 'Ireland'
	ISRAEL = 'Israel'
	ITALY = 'Italy'
	JAMAICA = 'Jamaica'
	JAPAN = 'Japan'
	JORDAN = 'Jordan'
	KAZAKHSTAN = 'Kazakhstan'
	KENYA = 'Kenya'
	LAOS = 'Laos'
	LATVIA = 'Latvia'
	LEBANON = 'Lebanon'
	LICHTENSTEIN = 'Lichtenstein'
	LITHUANIA = 'Lithuania'
	LUXEMBOURG = 'Luxembourg'
	MACAO = 'Macao'
	MACEDONIA = 'Macedonia'
	MALAYSIA = 'Malaysia'
	MALTA = 'Malta'
	MEXICO = 'Mexico'
	MONACO = 'Monaco'
	MONGOLIA = 'Mongolia'
	MONTENEGRO = 'Montenegro'
	MOROCCO = 'Morocco'
	NAMIBIA = 'Namibia'
	NEPAL = 'Nepal'
	NETHERLANDS = 'Netherlands'
	NEW_ZEALAND = 'New Zealand'
	NIGERIA = 'Nigeria'
	NORTH_KOREA = 'North Korea'
	NORWAY = 'Norway'
	PAKISTAN = 'Pakistan'
	PALESTINE = 'Palestine'
	PANAMA = 'Panama'
	PAPUA_NEW_GUINEA = 'Papua New Guinea'
	PARAGUAY = 'Paraguay'
	PERU = 'Peru'
	PHILIPPINES = 'Philippines'
	POLAND = 'Poland'
	PORTUGAL = 'Portugal'
	PUERTO_RICO = 'Puerto Rico'
	QATAR = 'Qatar'
	ROMANIA = 'Romania'
	RUSSIA = 'Russia'
	SAUDI_ARABIA = 'Saudi Arabia'
	SENEGAL = 'Senegal'
	SERBIA = 'Serbia'
	SERBIA_AND_MONTENEGRO = 'Serbia and Montenegro'
	SINGAPORE = 'Singapore'
	SLOVAKIA = 'Slovakia'
	SLOVENIA = 'Slovenia'
	SOUTH_AFRICAN_REPUBLIC = 'South African Republic'
	SOUTH_KOREA = 'South Korea'
	SPAIN = 'Spain'
	SWEDEN = 'Sweden'
	SWITZERLAND = 'Switzerland'
	SYRIA = 'Syria'
	TAIWAN = 'Taiwan'
	TANZANIA = 'Tanzania'
	THAILAND = 'Thailand'
	THE_SOVIET_UNION = 'The Soviet Union'
	TUNISIA = 'Tunisia'
	TURKEY = 'Turkey'
	UGANDA = 'Uganda'
	UKRAINE = 'Ukraine'
	UNITED_ARAB_EMIRATES = 'United Arab Emirates'
	UNITED_KINGDOM = 'United Kingdom'
	UNITED_STATES_OF_AMERICA = 'United States of America'
	URUGUAY = 'Uruguay'
	VENEZUELA = 'Venezuela'
	VIETNAM = 'Vietnam'
	WEST_GERMANY = 'West Germany'
	YUGOSLAVIA = 'Yugoslavia'
	ZIMBABWE = 'Zimbabwe'

language_lang = {
	LANG_CODE.AA: LANG.AFAR,
	LANG_CODE.AB: LANG.ABKHAZIAN,
	LANG_CODE.AF: LANG.AFRIKAANS,
	LANG_CODE.AM: LANG.AMHARIC,
	LANG_CODE.AR: LANG.ARABIC,
	LANG_CODE.AS: LANG.ASSAMESE,
	LANG_CODE.AY: LANG.AYMARA,
	LANG_CODE.AZ: LANG.AZERBAIJANI,
	LANG_CODE.BA: LANG.BASHKIR,
	LANG_CODE.BE: LANG.BYELORUSSIAN,
	LANG_CODE.BG: LANG.BULGARIAN,
	LANG_CODE.BH: LANG.BIHARI,
	LANG_CODE.BI: LANG.BISLAMA,
	LANG_CODE.BN: LANG.BENGALI_BANGLA,
	LANG_CODE.BO: LANG.TIBETAN,
	LANG_CODE.BR: LANG.BRETON,
	LANG_CODE.BS: LANG.BOSNIAN,
	LANG_CODE.CA: LANG.CATALAN,
	LANG_CODE.CO: LANG.CORSICAN,
	LANG_CODE.CS: LANG.CZECH,
	LANG_CODE.CN: LANG.CHINESE,
	LANG_CODE.CY: LANG.WELSH,
	LANG_CODE.DA: LANG.DANISH,
	LANG_CODE.DE: LANG.GERMAN,
	LANG_CODE.DZ: LANG.BHUTANI,
	LANG_CODE.EL: LANG.GREEK,
	LANG_CODE.EN: LANG.ENGLISH,
	LANG_CODE.EO: LANG.ESPERANTO,
	LANG_CODE.ES: LANG.SPANISH,
	LANG_CODE.ET: LANG.ESTONIAN,
	LANG_CODE.EU: LANG.BASQUE,
	LANG_CODE.FA: LANG.PERSIAN,
	LANG_CODE.FI: LANG.FINNISH,
	LANG_CODE.FJ: LANG.FIJI,
	LANG_CODE.FO: LANG.FAEROESE,
	LANG_CODE.FR: LANG.FRENCH,
	LANG_CODE.FY: LANG.FRISIAN,
	LANG_CODE.GA: LANG.IRISH,
	LANG_CODE.GD: LANG.SCOTS_GAELIC,
	LANG_CODE.GL: LANG.GALICIAN,
	LANG_CODE.GN: LANG.GUARANI,
	LANG_CODE.GU: LANG.GUJARATI,
	LANG_CODE.HA: LANG.HAUSA,
	LANG_CODE.HE: LANG.HEBREW,
	LANG_CODE.HI: LANG.HINDI,
	LANG_CODE.HR: LANG.CROATIAN,
	LANG_CODE.HU: LANG.HUNGARIAN,
	LANG_CODE.HY: LANG.ARMENIAN,
	LANG_CODE.IA: LANG.INTERLINGUA,
	LANG_CODE.ID: LANG.INDONESIAN,
	LANG_CODE.IE: LANG.INTERLINGUE,
	LANG_CODE.IK: LANG.INUPIAK,
	LANG_CODE.IS: LANG.ICELANDIC,
	LANG_CODE.IT: LANG.ITALIAN,
	LANG_CODE.IU: LANG.INUKTITUT,
	LANG_CODE.JA: LANG.JAPANESE,
	LANG_CODE.JI: LANG.YIDDISH,
	LANG_CODE.JW: LANG.JAVANESE,
	LANG_CODE.KA: LANG.GEORGIAN,
	LANG_CODE.KK: LANG.KAZAKH,
	LANG_CODE.KL: LANG.GREENLANDIC,
	LANG_CODE.KM: LANG.CAMBODIAN,
	LANG_CODE.KN: LANG.KANNADA,
	LANG_CODE.KO: LANG.KOREAN,
	LANG_CODE.KS: LANG.KASHMIRI,
	LANG_CODE.KU: LANG.KURDISH,
	LANG_CODE.KY: LANG.KIRGHIZ,
	LANG_CODE.LA: LANG.LATIN,
	LANG_CODE.LN: LANG.LINGALA,
	LANG_CODE.LO: LANG.LAOTHIAN,
	LANG_CODE.LT: LANG.LITHUANIAN,
	LANG_CODE.LV: LANG.LATVIAN_LETTISH,
	LANG_CODE.MG: LANG.MALAGASY,
	LANG_CODE.MI: LANG.MAORI,
	LANG_CODE.MK: LANG.MACEDONIAN,
	LANG_CODE.ML: LANG.MALAYALAM,
	LANG_CODE.MN: LANG.MONGOLIAN,
	LANG_CODE.MO: LANG.MOLDAVIAN,
	LANG_CODE.MR: LANG.MARATHI,
	LANG_CODE.MS: LANG.MALAY,
	LANG_CODE.MT: LANG.MALTESE,
	LANG_CODE.MY: LANG.BURMESE,
	LANG_CODE.NA: LANG.NAURU,
	LANG_CODE.NE: LANG.NEPALI,
	LANG_CODE.NL: LANG.DUTCH,
	LANG_CODE.NO: LANG.NORWEGIAN,
	LANG_CODE.OC: LANG.OCCITAN,
	LANG_CODE.OM: LANG.OROMO,
	LANG_CODE.OR: LANG.ORIYA,
	LANG_CODE.PA: LANG.PUNJABI,
	LANG_CODE.PL: LANG.POLISH,
	LANG_CODE.PS: LANG.PASHTO_PUSHTO,
	LANG_CODE.PT: LANG.PORTUGUESE,
	LANG_CODE.QU: LANG.QUECHUA,
	LANG_CODE.RM: LANG.RHAETO_ROMANCE,
	LANG_CODE.RN: LANG.KIRUNDI,
	LANG_CODE.RO: LANG.ROMANIAN,
	LANG_CODE.RU: LANG.RUSSIAN,
	LANG_CODE.RW: LANG.KINYARWANDA,
	LANG_CODE.SA: LANG.SANSKRIT,
	LANG_CODE.SD: LANG.SINDHI,
	LANG_CODE.SG: LANG.SANGRO,
	LANG_CODE.SH: LANG.SERBO_CROATIAN,
	LANG_CODE.SI: LANG.SINGHALESE,
	LANG_CODE.SK: LANG.SLOVAK,
	LANG_CODE.SL: LANG.SLOVENIAN,
	LANG_CODE.SM: LANG.SAMOAN,
	LANG_CODE.SN: LANG.SHONA,
	LANG_CODE.SO: LANG.SOMALI,
	LANG_CODE.SQ: LANG.ALBANIAN,
	LANG_CODE.SR: LANG.SERBIAN,
	LANG_CODE.SS: LANG.SISWATI,
	LANG_CODE.ST: LANG.SESOTHO,
	LANG_CODE.SU: LANG.SUNDANESE,
	LANG_CODE.SV: LANG.SWEDISH,
	LANG_CODE.SW: LANG.SWAHILI,
	LANG_CODE.TA: LANG.TAMIL,
	LANG_CODE.TE: LANG.TEGULU,
	LANG_CODE.TG: LANG.TAJIK,
	LANG_CODE.TH: LANG.THAI,
	LANG_CODE.TI: LANG.TIGRINYA,
	LANG_CODE.TK: LANG.TURKMEN,
	LANG_CODE.TL: LANG.TAGALOG,
	LANG_CODE.TN: LANG.SETSWANA,
	LANG_CODE.TO: LANG.TONGA,
	LANG_CODE.TR: LANG.TURKISH,
	LANG_CODE.TS: LANG.TSONGA,
	LANG_CODE.TT: LANG.TATAR,
	LANG_CODE.TW: LANG.TWI,
	LANG_CODE.UK: LANG.UKRAINIAN,
	LANG_CODE.UR: LANG.URDU,
	LANG_CODE.UZ: LANG.UZBEK,
	LANG_CODE.VI: LANG.VIETNAMESE,
	LANG_CODE.VO: LANG.VOLAPUK,
	LANG_CODE.WO: LANG.WOLOF,
	LANG_CODE.XH: LANG.XHOSA,
	LANG_CODE.XX: LANG.NO_LANGUAGE,
	LANG_CODE.YO: LANG.YORUBA,
	LANG_CODE.ZH: LANG.CHINESE,
	LANG_CODE.ZU: LANG.ZULU,
}

class GENRE:
	EROTIC = 'Erotic'
	PORNOGRAPHIC = 'Pornographic'
	ACTION = 'Action'
	ANIMATED = 'Animated'
	ANIMATION = 'Animation'
	ADVENTURE = 'Adventure'
	BIOGRAPHICAL = 'Biographical'
	CATASTROPHIC = 'Catastrophic'
	COMEDY = 'Comedy'
	COMPETITION = 'Competition'
	CRIME = 'Crime'
	DOCUMENTARY = 'Documentary'
	FAIRYTALE = 'Fairy Tale'
	DRAMA = 'Drama'
	FAMILY = 'Family'
	FANTASY = 'Fantasy'
	HISTORICAL = 'Historical'
	HORROR = 'Horror'
	IMAX = 'IMAX'
	EDUCATIONAL = 'Educational'
	MUSIC = 'Music'
	JOURNALISTIC = 'Journalistic'
	MILITARY = 'Military'
	MUSICAL = 'Musical'
	MYSTERIOUS = 'Mysterious'
	PSYCHOLOGICAL = 'Psychological'
	REALITY = 'Reality'
	ROMANTIC = 'Romantic'
	SCI_FI = 'Sci-Fi'
	SHORT = 'Short'
	SPORTS = 'Sports'
	STAND_UP = 'Stand-Up'
	TALK_SHOW = 'Talk-Show'
	TELENOVELA = 'Telenovela'
	THRILLER = 'Thriller'
	TRAVEL = 'Travel'
	WESTERN = 'Western'

genre_lang = {
	GENRE.EROTIC: LANG.EROTIC,
	GENRE.PORNOGRAPHIC: LANG.PORNOGRAPHIC,
	GENRE.ACTION: LANG.ACTION,
	GENRE.ANIMATED: LANG.ANIMATED,
	GENRE.ANIMATION: LANG.ANIMATION,
	GENRE.ADVENTURE: LANG.ADVENTURE,
	GENRE.BIOGRAPHICAL: LANG.BIOGRAPHICAL,
	GENRE.CATASTROPHIC: LANG.CATASTROPHIC,
	GENRE.COMEDY: LANG.COMEDY,
	GENRE.COMPETITION: LANG.COMPETITION,
	GENRE.CRIME: LANG.CRIME,
	GENRE.DOCUMENTARY: LANG.DOCUMENTARY,
	GENRE.FAIRYTALE: LANG.FAIRYTALE,
	GENRE.DRAMA: LANG.DRAMA,
	GENRE.FAMILY: LANG.FAMILY,
	GENRE.FANTASY: LANG.FANTASY,
	GENRE.HISTORICAL: LANG.HISTORICAL,
	GENRE.HORROR: LANG.HORROR,
	GENRE.IMAX: LANG.IMAX,
	GENRE.EDUCATIONAL: LANG.EDUCATIONAL,
	GENRE.MUSIC: LANG.MUSIC,
	GENRE.JOURNALISTIC: LANG.JOURNALISTIC,
	GENRE.MILITARY: LANG.MILITARY,
	GENRE.MUSICAL: LANG.MUSICAL,
	GENRE.MYSTERIOUS: LANG.MYSTERIOUS,
	GENRE.PSYCHOLOGICAL: LANG.PSYCHOLOGICAL,
	GENRE.REALITY: LANG.REALITY,
	GENRE.ROMANTIC: LANG.ROMANTIC,
	GENRE.SCI_FI: LANG.SCI_FI,
	GENRE.SHORT: LANG.SHORT,
	GENRE.SPORTS: LANG.SPORTS,
	GENRE.STAND_UP: LANG.STAND_UP,
	GENRE.TALK_SHOW: LANG.TALK_SHOW,
	GENRE.TELENOVELA: LANG.TELENOVELA,
	GENRE.THRILLER: LANG.THRILLER,
	GENRE.TRAVEL: LANG.TRAVEL,
	GENRE.WESTERN: LANG.WESTERN
}

country_lang = {
	COUNTRY.ALGERIA: LANG.ALGERIA,
	COUNTRY.ARGENTINA: LANG.ARGENTINA,
	COUNTRY.ARMENIA: LANG.ARMENIA,
	COUNTRY.ARUBA: LANG.ARUBA,
	COUNTRY.AUSTRALIA: LANG.AUSTRALIA,
	COUNTRY.AUSTRIA: LANG.AUSTRIA,
	COUNTRY.AZERBAIJAN: LANG.AZERBAIJAN,
	COUNTRY.BAHAMAS: LANG.BAHAMAS,
	COUNTRY.BANGLADESH: LANG.BANGLADESH,
	COUNTRY.BELARUS: LANG.BELARUS,
	COUNTRY.BELGIUM: LANG.BELGIUM,
	COUNTRY.BHUTAN: LANG.BHUTAN,
	COUNTRY.BOLIVIA: LANG.BOLIVIA,
	COUNTRY.BOSNIA_AND_HERZEGOVINA: LANG.BOSNIA_AND_HERZEGOVINA,
	COUNTRY.BOTSWANA: LANG.BOTSWANA,
	COUNTRY.BRAZIL: LANG.BRAZIL,
	COUNTRY.BRUNEI: LANG.BRUNEI,
	COUNTRY.BULGARIA: LANG.BULGARIA,
	COUNTRY.CAMBODIA: LANG.CAMBODIA,
	COUNTRY.CANADA: LANG.CANADA,
	COUNTRY.CHILE: LANG.CHILE,
	COUNTRY.CHINA: LANG.CHINA,
	COUNTRY.COLOMBIA: LANG.COLOMBIA,
	COUNTRY.COSTA_RICA: LANG.COSTA_RICA,
	COUNTRY.CROATIA: LANG.CROATIA,
	COUNTRY.CUBA: LANG.CUBA,
	COUNTRY.CYPRUS: LANG.CYPRUS,
	COUNTRY.CZECHIA: LANG.CZECHIA,
	COUNTRY.CZECHOSLOVAKIA: LANG.CZECHOSLOVAKIA,
	COUNTRY.DEMOCRATIC_REPUBLIC_OF_THE_CONGO: LANG.DEMOCRATIC_REPUBLIC_OF_THE_CONGO,
	COUNTRY.DENMARK: LANG.DENMARK,
	COUNTRY.DOMINICAN_REPUBLIC: LANG.DOMINICAN_REPUBLIC,
	COUNTRY.EAST_GERMANY: LANG.EAST_GERMANY,
	COUNTRY.EGYPT: LANG.EGYPT,
	COUNTRY.ESTONIA: LANG.ESTONIA,
	COUNTRY.FED_REP_YUGOSLAVIA: LANG.FED_REP_YUGOSLAVIA,
	COUNTRY.FINLAND: LANG.FINLAND,
	COUNTRY.FRANCE: LANG.FRANCE,
	COUNTRY.FRENCH_POLYNESIA: LANG.FRENCH_POLYNESIA,
	COUNTRY.GEORGIA: LANG.GEORGIA,
	COUNTRY.GERMAN_EMPIRE: LANG.GERMAN_EMPIRE,
	COUNTRY.GERMANY: LANG.GERMANY,
	COUNTRY.GHANA: LANG.GHANA,
	COUNTRY.GREECE: LANG.GREECE,
	COUNTRY.HAITI: LANG.HAITI,
	COUNTRY.HONG_KONG: LANG.HONG_KONG,
	COUNTRY.HUNGARY: LANG.HUNGARY,
	COUNTRY.ICELAND: LANG.ICELAND,
	COUNTRY.INDIA: LANG.INDIA,
	COUNTRY.INDONESIA: LANG.INDONESIA,
	COUNTRY.IRAN: LANG.IRAN,
	COUNTRY.IRAQ: LANG.IRAQ,
	COUNTRY.IRELAND: LANG.IRELAND,
	COUNTRY.ISRAEL: LANG.ISRAEL,
	COUNTRY.ITALY: LANG.ITALY,
	COUNTRY.JAMAICA: LANG.JAMAICA,
	COUNTRY.JAPAN: LANG.JAPAN,
	COUNTRY.JORDAN: LANG.JORDAN,
	COUNTRY.KAZAKHSTAN: LANG.KAZAKHSTAN,
	COUNTRY.KENYA: LANG.KENYA,
	COUNTRY.LAOS: LANG.LAOS,
	COUNTRY.LATVIA: LANG.LATVIA,
	COUNTRY.LEBANON: LANG.LEBANON,
	COUNTRY.LICHTENSTEIN: LANG.LICHTENSTEIN,
	COUNTRY.LITHUANIA: LANG.LITHUANIA,
	COUNTRY.LUXEMBOURG: LANG.LUXEMBOURG,
	COUNTRY.MACAO: LANG.MACAO,
	COUNTRY.MACEDONIA: LANG.MACEDONIA,
	COUNTRY.MALAYSIA: LANG.MALAYSIA,
	COUNTRY.MALTA: LANG.MALTA,
	COUNTRY.MEXICO: LANG.MEXICO,
	COUNTRY.MONACO: LANG.MONACO,
	COUNTRY.MONGOLIA: LANG.MONGOLIA,
	COUNTRY.MONTENEGRO: LANG.MONTENEGRO,
	COUNTRY.MOROCCO: LANG.MOROCCO,
	COUNTRY.NAMIBIA: LANG.NAMIBIA,
	COUNTRY.NEPAL: LANG.NEPAL,
	COUNTRY.NETHERLANDS: LANG.NETHERLANDS,
	COUNTRY.NEW_ZEALAND: LANG.NEW_ZEALAND,
	COUNTRY.NIGERIA: LANG.NIGERIA,
	COUNTRY.NORTH_KOREA: LANG.NORTH_KOREA,
	COUNTRY.NORWAY: LANG.NORWAY,
	COUNTRY.PAKISTAN: LANG.PAKISTAN,
	COUNTRY.PALESTINE: LANG.PALESTINE,
	COUNTRY.PANAMA: LANG.PANAMA,
	COUNTRY.PAPUA_NEW_GUINEA: LANG.PAPUA_NEW_GUINEA,
	COUNTRY.PARAGUAY: LANG.PARAGUAY,
	COUNTRY.PERU: LANG.PERU,
	COUNTRY.PHILIPPINES: LANG.PHILIPPINES,
	COUNTRY.POLAND: LANG.POLAND,
	COUNTRY.PORTUGAL: LANG.PORTUGAL,
	COUNTRY.PUERTO_RICO: LANG.PUERTO_RICO,
	COUNTRY.QATAR: LANG.QATAR,
	COUNTRY.ROMANIA: LANG.ROMANIA,
	COUNTRY.RUSSIA: LANG.RUSSIA,
	COUNTRY.SAUDI_ARABIA: LANG.SAUDI_ARABIA,
	COUNTRY.SENEGAL: LANG.SENEGAL,
	COUNTRY.SERBIA: LANG.SERBIA,
	COUNTRY.SERBIA_AND_MONTENEGRO: LANG.SERBIA_AND_MONTENEGRO,
	COUNTRY.SINGAPORE: LANG.SINGAPORE,
	COUNTRY.SLOVAKIA: LANG.SLOVAKIA,
	COUNTRY.SLOVENIA: LANG.SLOVENIA,
	COUNTRY.SOUTH_AFRICAN_REPUBLIC: LANG.SOUTH_AFRICAN_REPUBLIC,
	COUNTRY.SOUTH_KOREA: LANG.SOUTH_KOREA,
	COUNTRY.SPAIN: LANG.SPAIN,
	COUNTRY.SWEDEN: LANG.SWEDEN,
	COUNTRY.SWITZERLAND: LANG.SWITZERLAND,
	COUNTRY.SYRIA: LANG.SYRIA,
	COUNTRY.TAIWAN: LANG.TAIWAN,
	COUNTRY.TANZANIA: LANG.TANZANIA,
	COUNTRY.THAILAND: LANG.THAILAND,
	COUNTRY.THE_SOVIET_UNION: LANG.THE_SOVIET_UNION,
	COUNTRY.TUNISIA: LANG.TUNISIA,
	COUNTRY.TURKEY: LANG.TURKEY,
	COUNTRY.UGANDA: LANG.UGANDA,
	COUNTRY.UKRAINE: LANG.UKRAINE,
	COUNTRY.UNITED_ARAB_EMIRATES: LANG.UNITED_ARAB_EMIRATES,
	COUNTRY.UNITED_KINGDOM: LANG.UNITED_KINGDOM,
	COUNTRY.UNITED_STATES_OF_AMERICA: LANG.UNITED_STATES_OF_AMERICA,
	COUNTRY.URUGUAY: LANG.URUGUAY,
	COUNTRY.VENEZUELA: LANG.VENEZUELA,
	COUNTRY.VIETNAM: LANG.VIETNAM,
	COUNTRY.WEST_GERMANY: LANG.WEST_GERMANY,
	COUNTRY.YUGOSLAVIA: LANG.YUGOSLAVIA,
	COUNTRY.ZIMBABWE: LANG.ZIMBABWE,
}

explicit_genres = [GENRE.EROTIC, GENRE.PORNOGRAPHIC]

numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
common_chars = [' ', '-', ':']

alphabet = {
	LANG_CODE.CS: ['a', 'á', 'b', 'c', 'č', 'd', 'ď', 'e', 'é', 'ě', 'f', 'g', 'h', 'ch', 'i', 'í', 'j', 'k', 'l', 'm',
				   'n', 'ň', 'o', 'ó', 'p', 'q', 'r', 'ř', 's', 'š', 't', 'ť', 'u', 'ú', 'ů', 'v', 'w', 'x', 'y', 'ý',
				   'z', 'ž', ],
	LANG_CODE.SK: ['a', 'á', 'ä', 'b', 'c', 'č', 'd', 'ď', 'dz', 'dž', 'e', 'é', 'f', 'g', 'h', 'ch', 'i', 'í', 'j',
				   'k', 'l', 'ĺ', 'ľ', 'm', 'n', 'ň', 'o', 'ó', 'ô', 'p', 'q', 'r', 'ŕ', 's', 'š', 't', 'ť', 'u', 'ú',
				   'v', 'w', 'x', 'y', 'ý', 'z', 'ž'],
}

lang_countries = {
	LANG_CODE.CS: [COUNTRY.CZECHIA, COUNTRY.CZECHOSLOVAKIA],
	LANG_CODE.SK: [COUNTRY.SLOVAKIA, COUNTRY.CZECHOSLOVAKIA],
}

